[package]
name = "track-splitter"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
memmap2 = "0.9.9"
mp3lame-encoder = "0.2.1"
rayon = "1.11.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
